!!ExportedWorkflow
apiVersion: torq.io/v2alpha
kind: Workflow
id: 2cab49cc-c89b-4321-8164-9c635c889a0b
name: Wipro CI CD 2
trigger:
  onDemandTrigger:
    parameterList:
      parameters: []
playbook:
  steps:
    - name: us-docker.pkg.dev/stackpulse/public/utils/output_utils/print:2.8.0
      id: print_a_message_to_stdout
      env:
        __TQ_FILE_ENV_PARSER__FILE_OR_STRING: plain-text
        FILE_OR_STRING: '{{ $.metadata.workflow_id }}'
      uuid: d2bbac4d-b9dd-4217-89a6-451ea584dcb1
      pretty_name: Print a message to stdout
      options:
        executor:
          name: utils_infrastructure_v_1_72_0
          env: {}
          sync: true
          disable: false
      manifestId: d42cab37-acff-8094-9e36-52285f636094
      isPrivate: false
      isPrivateUrl: true
      mock_output:
        enabled: false
      skip: false
      retry: {}
  output_schema: '{}'
  tags:
    - wipro
root: true
